@set allusersprofile=c:\programdata
@set appdata=c:\users\ding\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-1r3f213
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\ding
@set include=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\atlmfc\include;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.16299.0\shared;c:\program files (x86)\windows kits\10\include\10.0.16299.0\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\winrt
@set lib=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\lib\x86;c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0;c:\program files (x86)\windows kits\10\references\10.0.16299.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\ding\appdata\local
@set logonserver=\\desktop-1r3f213
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set mysql_home=e:\mysql-5.7.21-win32
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set onedrive=c:\users\ding\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild\15.0\bin\roslyn;c:\program files (x86)\microsoft visual studio\2017\enterprise\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\windows kits\10\bin\10.0.16299.0\x86;c:\program files (x86)\microsoft visual studio\2017\enterprise\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\;c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\github\github\lib\win32\x86;c:\perl64\site\bin;c:\perl64\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\tortoisesvn\bin;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\cmake\bin;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;e:\mysql-5.7.21-win32\bin;c:\python27;c:\program files\tortoisegit\bin;c:\program files\git\cmd;c:\nasm-2.13.03;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\svn\bin;c:\users\ding\appdata\local\microsoft\windowsapps;c:\program files\microsoft vs code\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\ding\appdata\local\microsoft\visualstudio\15.0_40e41093\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 42 stepping 7, genuineintel
@set processor_level=6
@set processor_revision=2a07
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\microsoft visual studio\2017\enterprise\msbuild
@set pvs_vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\ding\appdata\local\temp
@set tmp=c:\users\ding\appdata\local\temp
@set ucrtversion=10.0.16299.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-1r3f213
@set userdomain_roamingprofile=desktop-1r3f213
@set username=ding
@set userprofile=c:\users\ding
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.12.25827\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\redist\msvc\14.12.25810\
@set vctoolsversion=14.12.25827
@set visualstudiodir=c:\users\ding\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio enterprise 2017
@set visualstudioversion=15.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vs150comntools=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.5.7
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2017\enterprise\
@set vslang=2052
@set vssdk140install=c:\program files (x86)\microsoft visual studio 14.0\vssdk\
@set vssdk150install=c:\program files (x86)\microsoft visual studio\2017\enterprise\vssdk
@set vsskuedition=enterprise
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0;c:\program files (x86)\windows kits\10\references\10.0.16299.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.16299.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.16299.0\
@set windowssdkversion=10.0.16299.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2017\enterprise\common7\ide\extensions\github\github\lib\win32\x86;c:\perl64\site\bin;c:\perl64\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\tortoisesvn\bin;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\cmake\bin;c:\program files (x86)\visual leak detector\bin\win32;c:\program files (x86)\visual leak detector\bin\win64;e:\mysql-5.7.21-win32\bin;c:\python27;c:\program files\tortoisegit\bin;c:\program files\git\cmd;c:\nasm-2.13.03;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\svn\bin;c:\users\ding\appdata\local\microsoft\windowsapps;c:\program files\microsoft vs code\bin

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" --driver-mode=cl @"C:\mytest\server\NameCheckServer\main.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1