// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMsg.proto

#ifndef PROTOBUF_ServerMsg_2eproto_INCLUDED
#define PROTOBUF_ServerMsg_2eproto_INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ServerMsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[11];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPingImpl();
void InitDefaultsPing();
void InitDefaultsServerRegisterImpl();
void InitDefaultsServerRegister();
void InitDefaultsServerRegisterRetImpl();
void InitDefaultsServerRegisterRet();
void InitDefaultsServerLoadInfoImpl();
void InitDefaultsServerLoadInfo();
void InitDefaultsUpdateServerLoadImpl();
void InitDefaultsUpdateServerLoad();
void InitDefaultsAddNewClientImpl();
void InitDefaultsAddNewClient();
void InitDefaultsDelClientImpl();
void InitDefaultsDelClient();
void InitDefaultsClientTokenImpl();
void InitDefaultsClientToken();
void InitDefaultsLoadPlayerDataImpl();
void InitDefaultsLoadPlayerData();
void InitDefaultsLoadPlayerDataRetImpl();
void InitDefaultsLoadPlayerDataRet();
void InitDefaultsServerLogImpl();
void InitDefaultsServerLog();
inline void InitDefaults() {
  InitDefaultsPing();
  InitDefaultsServerRegister();
  InitDefaultsServerRegisterRet();
  InitDefaultsServerLoadInfo();
  InitDefaultsUpdateServerLoad();
  InitDefaultsAddNewClient();
  InitDefaultsDelClient();
  InitDefaultsClientToken();
  InitDefaultsLoadPlayerData();
  InitDefaultsLoadPlayerDataRet();
  InitDefaultsServerLog();
}
}  // namespace protobuf_ServerMsg_2eproto
namespace svrData {
class AddNewClient;
class AddNewClientDefaultTypeInternal;
extern AddNewClientDefaultTypeInternal _AddNewClient_default_instance_;
class ClientToken;
class ClientTokenDefaultTypeInternal;
extern ClientTokenDefaultTypeInternal _ClientToken_default_instance_;
class DelClient;
class DelClientDefaultTypeInternal;
extern DelClientDefaultTypeInternal _DelClient_default_instance_;
class LoadPlayerData;
class LoadPlayerDataDefaultTypeInternal;
extern LoadPlayerDataDefaultTypeInternal _LoadPlayerData_default_instance_;
class LoadPlayerDataRet;
class LoadPlayerDataRetDefaultTypeInternal;
extern LoadPlayerDataRetDefaultTypeInternal _LoadPlayerDataRet_default_instance_;
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;
class ServerLoadInfo;
class ServerLoadInfoDefaultTypeInternal;
extern ServerLoadInfoDefaultTypeInternal _ServerLoadInfo_default_instance_;
class ServerLog;
class ServerLogDefaultTypeInternal;
extern ServerLogDefaultTypeInternal _ServerLog_default_instance_;
class ServerRegister;
class ServerRegisterDefaultTypeInternal;
extern ServerRegisterDefaultTypeInternal _ServerRegister_default_instance_;
class ServerRegisterRet;
class ServerRegisterRetDefaultTypeInternal;
extern ServerRegisterRetDefaultTypeInternal _ServerRegisterRet_default_instance_;
class UpdateServerLoad;
class UpdateServerLoadDefaultTypeInternal;
extern UpdateServerLoadDefaultTypeInternal _UpdateServerLoad_default_instance_;
}  // namespace svrData
namespace google {
namespace protobuf {
template<> ::svrData::AddNewClient* Arena::Create< ::svrData::AddNewClient>(Arena*);
template<> ::svrData::ClientToken* Arena::Create< ::svrData::ClientToken>(Arena*);
template<> ::svrData::DelClient* Arena::Create< ::svrData::DelClient>(Arena*);
template<> ::svrData::LoadPlayerData* Arena::Create< ::svrData::LoadPlayerData>(Arena*);
template<> ::svrData::LoadPlayerDataRet* Arena::Create< ::svrData::LoadPlayerDataRet>(Arena*);
template<> ::svrData::Ping* Arena::Create< ::svrData::Ping>(Arena*);
template<> ::svrData::ServerLoadInfo* Arena::Create< ::svrData::ServerLoadInfo>(Arena*);
template<> ::svrData::ServerLog* Arena::Create< ::svrData::ServerLog>(Arena*);
template<> ::svrData::ServerRegister* Arena::Create< ::svrData::ServerRegister>(Arena*);
template<> ::svrData::ServerRegisterRet* Arena::Create< ::svrData::ServerRegisterRet>(Arena*);
template<> ::svrData::UpdateServerLoad* Arena::Create< ::svrData::UpdateServerLoad>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace svrData {

enum ServerRegisterRet_EC {
  ServerRegisterRet_EC_EC_OTHER = 0,
  ServerRegisterRet_EC_EC_SUCC = 1,
  ServerRegisterRet_EC_EC_SERVER_ID_EXIST = 2,
  ServerRegisterRet_EC_EC_TO_CONNECT_ID_NOT_EQUAL = 3,
  ServerRegisterRet_EC_ServerRegisterRet_EC_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ServerRegisterRet_EC_ServerRegisterRet_EC_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ServerRegisterRet_EC_IsValid(int value);
const ServerRegisterRet_EC ServerRegisterRet_EC_EC_MIN = ServerRegisterRet_EC_EC_OTHER;
const ServerRegisterRet_EC ServerRegisterRet_EC_EC_MAX = ServerRegisterRet_EC_EC_TO_CONNECT_ID_NOT_EQUAL;
const int ServerRegisterRet_EC_EC_ARRAYSIZE = ServerRegisterRet_EC_EC_MAX + 1;

const ::google::protobuf::EnumDescriptor* ServerRegisterRet_EC_descriptor();
inline const ::std::string& ServerRegisterRet_EC_Name(ServerRegisterRet_EC value) {
  return ::google::protobuf::internal::NameOfEnum(
    ServerRegisterRet_EC_descriptor(), value);
}
inline bool ServerRegisterRet_EC_Parse(
    const ::std::string& name, ServerRegisterRet_EC* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ServerRegisterRet_EC>(
    ServerRegisterRet_EC_descriptor(), name, value);
}
enum LoadPlayerDataRet_EC {
  LoadPlayerDataRet_EC_EC_OTHER = 0,
  LoadPlayerDataRet_EC_EC_SUCC = 1,
  LoadPlayerDataRet_EC_LoadPlayerDataRet_EC_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LoadPlayerDataRet_EC_LoadPlayerDataRet_EC_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LoadPlayerDataRet_EC_IsValid(int value);
const LoadPlayerDataRet_EC LoadPlayerDataRet_EC_EC_MIN = LoadPlayerDataRet_EC_EC_OTHER;
const LoadPlayerDataRet_EC LoadPlayerDataRet_EC_EC_MAX = LoadPlayerDataRet_EC_EC_SUCC;
const int LoadPlayerDataRet_EC_EC_ARRAYSIZE = LoadPlayerDataRet_EC_EC_MAX + 1;

const ::google::protobuf::EnumDescriptor* LoadPlayerDataRet_EC_descriptor();
inline const ::std::string& LoadPlayerDataRet_EC_Name(LoadPlayerDataRet_EC value) {
  return ::google::protobuf::internal::NameOfEnum(
    LoadPlayerDataRet_EC_descriptor(), value);
}
inline bool LoadPlayerDataRet_EC_Parse(
    const ::std::string& name, LoadPlayerDataRet_EC* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LoadPlayerDataRet_EC>(
    LoadPlayerDataRet_EC_descriptor(), name, value);
}
// ===================================================================

class Ping : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ping(Ping&& from) noexcept
    : Ping() {
    *this = ::std::move(from);
  }

  inline Ping& operator=(Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Ping* other);
  friend void swap(Ping& a, Ping& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ping* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Ping>(NULL);
  }

  Ping* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<Ping>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Ping* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:svrData.Ping)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsPingImpl();
};
// -------------------------------------------------------------------

class ServerRegister : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.ServerRegister) */ {
 public:
  ServerRegister();
  virtual ~ServerRegister();

  ServerRegister(const ServerRegister& from);

  inline ServerRegister& operator=(const ServerRegister& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerRegister(ServerRegister&& from) noexcept
    : ServerRegister() {
    *this = ::std::move(from);
  }

  inline ServerRegister& operator=(ServerRegister&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRegister& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerRegister* internal_default_instance() {
    return reinterpret_cast<const ServerRegister*>(
               &_ServerRegister_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ServerRegister* other);
  friend void swap(ServerRegister& a, ServerRegister& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerRegister* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerRegister>(NULL);
  }

  ServerRegister* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerRegister>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerRegister& from);
  void MergeFrom(const ServerRegister& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerRegister* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 nServerID = 1;
  void clear_nserverid();
  static const int kNServerIDFieldNumber = 1;
  ::google::protobuf::int32 nserverid() const;
  void set_nserverid(::google::protobuf::int32 value);

  // int32 nServerType = 2;
  void clear_nservertype();
  static const int kNServerTypeFieldNumber = 2;
  ::google::protobuf::int32 nservertype() const;
  void set_nservertype(::google::protobuf::int32 value);

  // int32 nConnectID = 3;
  void clear_nconnectid();
  static const int kNConnectIDFieldNumber = 3;
  ::google::protobuf::int32 nconnectid() const;
  void set_nconnectid(::google::protobuf::int32 value);

  // int32 nPort = 4;
  void clear_nport();
  static const int kNPortFieldNumber = 4;
  ::google::protobuf::int32 nport() const;
  void set_nport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.ServerRegister)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 nserverid_;
  ::google::protobuf::int32 nservertype_;
  ::google::protobuf::int32 nconnectid_;
  ::google::protobuf::int32 nport_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsServerRegisterImpl();
};
// -------------------------------------------------------------------

class ServerRegisterRet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.ServerRegisterRet) */ {
 public:
  ServerRegisterRet();
  virtual ~ServerRegisterRet();

  ServerRegisterRet(const ServerRegisterRet& from);

  inline ServerRegisterRet& operator=(const ServerRegisterRet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerRegisterRet(ServerRegisterRet&& from) noexcept
    : ServerRegisterRet() {
    *this = ::std::move(from);
  }

  inline ServerRegisterRet& operator=(ServerRegisterRet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerRegisterRet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerRegisterRet* internal_default_instance() {
    return reinterpret_cast<const ServerRegisterRet*>(
               &_ServerRegisterRet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ServerRegisterRet* other);
  friend void swap(ServerRegisterRet& a, ServerRegisterRet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerRegisterRet* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerRegisterRet>(NULL);
  }

  ServerRegisterRet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerRegisterRet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerRegisterRet& from);
  void MergeFrom(const ServerRegisterRet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerRegisterRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ServerRegisterRet_EC EC;
  static const EC EC_OTHER =
    ServerRegisterRet_EC_EC_OTHER;
  static const EC EC_SUCC =
    ServerRegisterRet_EC_EC_SUCC;
  static const EC EC_SERVER_ID_EXIST =
    ServerRegisterRet_EC_EC_SERVER_ID_EXIST;
  static const EC EC_TO_CONNECT_ID_NOT_EQUAL =
    ServerRegisterRet_EC_EC_TO_CONNECT_ID_NOT_EQUAL;
  static inline bool EC_IsValid(int value) {
    return ServerRegisterRet_EC_IsValid(value);
  }
  static const EC EC_MIN =
    ServerRegisterRet_EC_EC_MIN;
  static const EC EC_MAX =
    ServerRegisterRet_EC_EC_MAX;
  static const int EC_ARRAYSIZE =
    ServerRegisterRet_EC_EC_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  EC_descriptor() {
    return ServerRegisterRet_EC_descriptor();
  }
  static inline const ::std::string& EC_Name(EC value) {
    return ServerRegisterRet_EC_Name(value);
  }
  static inline bool EC_Parse(const ::std::string& name,
      EC* value) {
    return ServerRegisterRet_EC_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string sIP = 2;
  void clear_sip();
  static const int kSIPFieldNumber = 2;
  const ::std::string& sip() const;
  void set_sip(const ::std::string& value);
  #if LANG_CXX11
  void set_sip(::std::string&& value);
  #endif
  void set_sip(const char* value);
  void set_sip(const char* value, size_t size);
  ::std::string* mutable_sip();
  ::std::string* release_sip();
  void set_allocated_sip(::std::string* sip);

  // int32 nRetCode = 1;
  void clear_nretcode();
  static const int kNRetCodeFieldNumber = 1;
  ::google::protobuf::int32 nretcode() const;
  void set_nretcode(::google::protobuf::int32 value);

  // int32 nPort = 3;
  void clear_nport();
  static const int kNPortFieldNumber = 3;
  ::google::protobuf::int32 nport() const;
  void set_nport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.ServerRegisterRet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sip_;
  ::google::protobuf::int32 nretcode_;
  ::google::protobuf::int32 nport_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsServerRegisterRetImpl();
};
// -------------------------------------------------------------------

class ServerLoadInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.ServerLoadInfo) */ {
 public:
  ServerLoadInfo();
  virtual ~ServerLoadInfo();

  ServerLoadInfo(const ServerLoadInfo& from);

  inline ServerLoadInfo& operator=(const ServerLoadInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerLoadInfo(ServerLoadInfo&& from) noexcept
    : ServerLoadInfo() {
    *this = ::std::move(from);
  }

  inline ServerLoadInfo& operator=(ServerLoadInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerLoadInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerLoadInfo* internal_default_instance() {
    return reinterpret_cast<const ServerLoadInfo*>(
               &_ServerLoadInfo_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ServerLoadInfo* other);
  friend void swap(ServerLoadInfo& a, ServerLoadInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerLoadInfo* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerLoadInfo>(NULL);
  }

  ServerLoadInfo* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerLoadInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerLoadInfo& from);
  void MergeFrom(const ServerLoadInfo& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerLoadInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sIP = 4;
  void clear_sip();
  static const int kSIPFieldNumber = 4;
  const ::std::string& sip() const;
  void set_sip(const ::std::string& value);
  #if LANG_CXX11
  void set_sip(::std::string&& value);
  #endif
  void set_sip(const char* value);
  void set_sip(const char* value, size_t size);
  ::std::string* mutable_sip();
  ::std::string* release_sip();
  void set_allocated_sip(::std::string* sip);

  // int32 nMaxClient = 1;
  void clear_nmaxclient();
  static const int kNMaxClientFieldNumber = 1;
  ::google::protobuf::int32 nmaxclient() const;
  void set_nmaxclient(::google::protobuf::int32 value);

  // int32 nNowClient = 2;
  void clear_nnowclient();
  static const int kNNowClientFieldNumber = 2;
  ::google::protobuf::int32 nnowclient() const;
  void set_nnowclient(::google::protobuf::int32 value);

  // int32 nPort = 3;
  void clear_nport();
  static const int kNPortFieldNumber = 3;
  ::google::protobuf::int32 nport() const;
  void set_nport(::google::protobuf::int32 value);

  // int32 nSubServerID = 5;
  void clear_nsubserverid();
  static const int kNSubServerIDFieldNumber = 5;
  ::google::protobuf::int32 nsubserverid() const;
  void set_nsubserverid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.ServerLoadInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sip_;
  ::google::protobuf::int32 nmaxclient_;
  ::google::protobuf::int32 nnowclient_;
  ::google::protobuf::int32 nport_;
  ::google::protobuf::int32 nsubserverid_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsServerLoadInfoImpl();
};
// -------------------------------------------------------------------

class UpdateServerLoad : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.UpdateServerLoad) */ {
 public:
  UpdateServerLoad();
  virtual ~UpdateServerLoad();

  UpdateServerLoad(const UpdateServerLoad& from);

  inline UpdateServerLoad& operator=(const UpdateServerLoad& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UpdateServerLoad(UpdateServerLoad&& from) noexcept
    : UpdateServerLoad() {
    *this = ::std::move(from);
  }

  inline UpdateServerLoad& operator=(UpdateServerLoad&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateServerLoad& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UpdateServerLoad* internal_default_instance() {
    return reinterpret_cast<const UpdateServerLoad*>(
               &_UpdateServerLoad_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(UpdateServerLoad* other);
  friend void swap(UpdateServerLoad& a, UpdateServerLoad& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UpdateServerLoad* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<UpdateServerLoad>(NULL);
  }

  UpdateServerLoad* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<UpdateServerLoad>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UpdateServerLoad& from);
  void MergeFrom(const UpdateServerLoad& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UpdateServerLoad* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 nClientCountNow = 1;
  void clear_nclientcountnow();
  static const int kNClientCountNowFieldNumber = 1;
  ::google::protobuf::int32 nclientcountnow() const;
  void set_nclientcountnow(::google::protobuf::int32 value);

  // int32 nClientCountMax = 2;
  void clear_nclientcountmax();
  static const int kNClientCountMaxFieldNumber = 2;
  ::google::protobuf::int32 nclientcountmax() const;
  void set_nclientcountmax(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.UpdateServerLoad)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 nclientcountnow_;
  ::google::protobuf::int32 nclientcountmax_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsUpdateServerLoadImpl();
};
// -------------------------------------------------------------------

class AddNewClient : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.AddNewClient) */ {
 public:
  AddNewClient();
  virtual ~AddNewClient();

  AddNewClient(const AddNewClient& from);

  inline AddNewClient& operator=(const AddNewClient& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AddNewClient(AddNewClient&& from) noexcept
    : AddNewClient() {
    *this = ::std::move(from);
  }

  inline AddNewClient& operator=(AddNewClient&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddNewClient& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddNewClient* internal_default_instance() {
    return reinterpret_cast<const AddNewClient*>(
               &_AddNewClient_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(AddNewClient* other);
  friend void swap(AddNewClient& a, AddNewClient& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AddNewClient* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<AddNewClient>(NULL);
  }

  AddNewClient* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<AddNewClient>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddNewClient& from);
  void MergeFrom(const AddNewClient& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddNewClient* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:svrData.AddNewClient)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsAddNewClientImpl();
};
// -------------------------------------------------------------------

class DelClient : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.DelClient) */ {
 public:
  DelClient();
  virtual ~DelClient();

  DelClient(const DelClient& from);

  inline DelClient& operator=(const DelClient& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DelClient(DelClient&& from) noexcept
    : DelClient() {
    *this = ::std::move(from);
  }

  inline DelClient& operator=(DelClient&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DelClient& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DelClient* internal_default_instance() {
    return reinterpret_cast<const DelClient*>(
               &_DelClient_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(DelClient* other);
  friend void swap(DelClient& a, DelClient& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DelClient* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<DelClient>(NULL);
  }

  DelClient* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<DelClient>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DelClient& from);
  void MergeFrom(const DelClient& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DelClient* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 nClientID = 1;
  void clear_nclientid();
  static const int kNClientIDFieldNumber = 1;
  ::google::protobuf::int32 nclientid() const;
  void set_nclientid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.DelClient)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 nclientid_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsDelClientImpl();
};
// -------------------------------------------------------------------

class ClientToken : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.ClientToken) */ {
 public:
  ClientToken();
  virtual ~ClientToken();

  ClientToken(const ClientToken& from);

  inline ClientToken& operator=(const ClientToken& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ClientToken(ClientToken&& from) noexcept
    : ClientToken() {
    *this = ::std::move(from);
  }

  inline ClientToken& operator=(ClientToken&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientToken& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientToken* internal_default_instance() {
    return reinterpret_cast<const ClientToken*>(
               &_ClientToken_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(ClientToken* other);
  friend void swap(ClientToken& a, ClientToken& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ClientToken* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ClientToken>(NULL);
  }

  ClientToken* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ClientToken>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ClientToken& from);
  void MergeFrom(const ClientToken& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ClientToken* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sEtoken = 1;
  void clear_setoken();
  static const int kSEtokenFieldNumber = 1;
  const ::std::string& setoken() const;
  void set_setoken(const ::std::string& value);
  #if LANG_CXX11
  void set_setoken(::std::string&& value);
  #endif
  void set_setoken(const char* value);
  void set_setoken(const char* value, size_t size);
  ::std::string* mutable_setoken();
  ::std::string* release_setoken();
  void set_allocated_setoken(::std::string* setoken);

  // bytes sSecret = 2;
  void clear_ssecret();
  static const int kSSecretFieldNumber = 2;
  const ::std::string& ssecret() const;
  void set_ssecret(const ::std::string& value);
  #if LANG_CXX11
  void set_ssecret(::std::string&& value);
  #endif
  void set_ssecret(const char* value);
  void set_ssecret(const void* value, size_t size);
  ::std::string* mutable_ssecret();
  ::std::string* release_ssecret();
  void set_allocated_ssecret(::std::string* ssecret);

  // @@protoc_insertion_point(class_scope:svrData.ClientToken)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr setoken_;
  ::google::protobuf::internal::ArenaStringPtr ssecret_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsClientTokenImpl();
};
// -------------------------------------------------------------------

class LoadPlayerData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.LoadPlayerData) */ {
 public:
  LoadPlayerData();
  virtual ~LoadPlayerData();

  LoadPlayerData(const LoadPlayerData& from);

  inline LoadPlayerData& operator=(const LoadPlayerData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoadPlayerData(LoadPlayerData&& from) noexcept
    : LoadPlayerData() {
    *this = ::std::move(from);
  }

  inline LoadPlayerData& operator=(LoadPlayerData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoadPlayerData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPlayerData* internal_default_instance() {
    return reinterpret_cast<const LoadPlayerData*>(
               &_LoadPlayerData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(LoadPlayerData* other);
  friend void swap(LoadPlayerData& a, LoadPlayerData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoadPlayerData* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<LoadPlayerData>(NULL);
  }

  LoadPlayerData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<LoadPlayerData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoadPlayerData& from);
  void MergeFrom(const LoadPlayerData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoadPlayerData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string account = 2;
  void clear_account();
  static const int kAccountFieldNumber = 2;
  const ::std::string& account() const;
  void set_account(const ::std::string& value);
  #if LANG_CXX11
  void set_account(::std::string&& value);
  #endif
  void set_account(const char* value);
  void set_account(const char* value, size_t size);
  ::std::string* mutable_account();
  ::std::string* release_account();
  void set_allocated_account(::std::string* account);

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // bytes data = 14;
  void clear_data();
  static const int kDataFieldNumber = 14;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // int64 clientid = 1;
  void clear_clientid();
  static const int kClientidFieldNumber = 1;
  ::google::protobuf::int64 clientid() const;
  void set_clientid(::google::protobuf::int64 value);

  // int64 guid = 4;
  void clear_guid();
  static const int kGuidFieldNumber = 4;
  ::google::protobuf::int64 guid() const;
  void set_guid(::google::protobuf::int64 value);

  // int32 sex = 5;
  void clear_sex();
  static const int kSexFieldNumber = 5;
  ::google::protobuf::int32 sex() const;
  void set_sex(::google::protobuf::int32 value);

  // int32 job = 6;
  void clear_job();
  static const int kJobFieldNumber = 6;
  ::google::protobuf::int32 job() const;
  void set_job(::google::protobuf::int32 value);

  // int32 level = 7;
  void clear_level();
  static const int kLevelFieldNumber = 7;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // int32 createtime = 8;
  void clear_createtime();
  static const int kCreatetimeFieldNumber = 8;
  ::google::protobuf::int32 createtime() const;
  void set_createtime(::google::protobuf::int32 value);

  // int32 logintime = 9;
  void clear_logintime();
  static const int kLogintimeFieldNumber = 9;
  ::google::protobuf::int32 logintime() const;
  void set_logintime(::google::protobuf::int32 value);

  // int32 mapid = 10;
  void clear_mapid();
  static const int kMapidFieldNumber = 10;
  ::google::protobuf::int32 mapid() const;
  void set_mapid(::google::protobuf::int32 value);

  // float x = 11;
  void clear_x();
  static const int kXFieldNumber = 11;
  float x() const;
  void set_x(float value);

  // float y = 12;
  void clear_y();
  static const int kYFieldNumber = 12;
  float y() const;
  void set_y(float value);

  // float z = 13;
  void clear_z();
  static const int kZFieldNumber = 13;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:svrData.LoadPlayerData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr account_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int64 clientid_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 sex_;
  ::google::protobuf::int32 job_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 createtime_;
  ::google::protobuf::int32 logintime_;
  ::google::protobuf::int32 mapid_;
  float x_;
  float y_;
  float z_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsLoadPlayerDataImpl();
};
// -------------------------------------------------------------------

class LoadPlayerDataRet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.LoadPlayerDataRet) */ {
 public:
  LoadPlayerDataRet();
  virtual ~LoadPlayerDataRet();

  LoadPlayerDataRet(const LoadPlayerDataRet& from);

  inline LoadPlayerDataRet& operator=(const LoadPlayerDataRet& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LoadPlayerDataRet(LoadPlayerDataRet&& from) noexcept
    : LoadPlayerDataRet() {
    *this = ::std::move(from);
  }

  inline LoadPlayerDataRet& operator=(LoadPlayerDataRet&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoadPlayerDataRet& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LoadPlayerDataRet* internal_default_instance() {
    return reinterpret_cast<const LoadPlayerDataRet*>(
               &_LoadPlayerDataRet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(LoadPlayerDataRet* other);
  friend void swap(LoadPlayerDataRet& a, LoadPlayerDataRet& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LoadPlayerDataRet* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<LoadPlayerDataRet>(NULL);
  }

  LoadPlayerDataRet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<LoadPlayerDataRet>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LoadPlayerDataRet& from);
  void MergeFrom(const LoadPlayerDataRet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LoadPlayerDataRet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef LoadPlayerDataRet_EC EC;
  static const EC EC_OTHER =
    LoadPlayerDataRet_EC_EC_OTHER;
  static const EC EC_SUCC =
    LoadPlayerDataRet_EC_EC_SUCC;
  static inline bool EC_IsValid(int value) {
    return LoadPlayerDataRet_EC_IsValid(value);
  }
  static const EC EC_MIN =
    LoadPlayerDataRet_EC_EC_MIN;
  static const EC EC_MAX =
    LoadPlayerDataRet_EC_EC_MAX;
  static const int EC_ARRAYSIZE =
    LoadPlayerDataRet_EC_EC_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  EC_descriptor() {
    return LoadPlayerDataRet_EC_descriptor();
  }
  static inline const ::std::string& EC_Name(EC value) {
    return LoadPlayerDataRet_EC_Name(value);
  }
  static inline bool EC_Parse(const ::std::string& name,
      EC* value) {
    return LoadPlayerDataRet_EC_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // int32 nRetCode = 1;
  void clear_nretcode();
  static const int kNRetCodeFieldNumber = 1;
  ::google::protobuf::int32 nretcode() const;
  void set_nretcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:svrData.LoadPlayerDataRet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 nretcode_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsLoadPlayerDataRetImpl();
};
// -------------------------------------------------------------------

class ServerLog : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svrData.ServerLog) */ {
 public:
  ServerLog();
  virtual ~ServerLog();

  ServerLog(const ServerLog& from);

  inline ServerLog& operator=(const ServerLog& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ServerLog(ServerLog&& from) noexcept
    : ServerLog() {
    *this = ::std::move(from);
  }

  inline ServerLog& operator=(ServerLog&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerLog& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerLog* internal_default_instance() {
    return reinterpret_cast<const ServerLog*>(
               &_ServerLog_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(ServerLog* other);
  friend void swap(ServerLog& a, ServerLog& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ServerLog* New() const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerLog>(NULL);
  }

  ServerLog* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL {
    return ::google::protobuf::Arena::Create<ServerLog>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ServerLog& from);
  void MergeFrom(const ServerLog& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ServerLog* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:svrData.ServerLog)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_ServerMsg_2eproto::TableStruct;
  friend void ::protobuf_ServerMsg_2eproto::InitDefaultsServerLogImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ping

// -------------------------------------------------------------------

// ServerRegister

// int32 nServerID = 1;
inline void ServerRegister::clear_nserverid() {
  nserverid_ = 0;
}
inline ::google::protobuf::int32 ServerRegister::nserverid() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegister.nServerID)
  return nserverid_;
}
inline void ServerRegister::set_nserverid(::google::protobuf::int32 value) {
  
  nserverid_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegister.nServerID)
}

// int32 nServerType = 2;
inline void ServerRegister::clear_nservertype() {
  nservertype_ = 0;
}
inline ::google::protobuf::int32 ServerRegister::nservertype() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegister.nServerType)
  return nservertype_;
}
inline void ServerRegister::set_nservertype(::google::protobuf::int32 value) {
  
  nservertype_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegister.nServerType)
}

// int32 nConnectID = 3;
inline void ServerRegister::clear_nconnectid() {
  nconnectid_ = 0;
}
inline ::google::protobuf::int32 ServerRegister::nconnectid() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegister.nConnectID)
  return nconnectid_;
}
inline void ServerRegister::set_nconnectid(::google::protobuf::int32 value) {
  
  nconnectid_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegister.nConnectID)
}

// int32 nPort = 4;
inline void ServerRegister::clear_nport() {
  nport_ = 0;
}
inline ::google::protobuf::int32 ServerRegister::nport() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegister.nPort)
  return nport_;
}
inline void ServerRegister::set_nport(::google::protobuf::int32 value) {
  
  nport_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegister.nPort)
}

// -------------------------------------------------------------------

// ServerRegisterRet

// int32 nRetCode = 1;
inline void ServerRegisterRet::clear_nretcode() {
  nretcode_ = 0;
}
inline ::google::protobuf::int32 ServerRegisterRet::nretcode() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegisterRet.nRetCode)
  return nretcode_;
}
inline void ServerRegisterRet::set_nretcode(::google::protobuf::int32 value) {
  
  nretcode_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegisterRet.nRetCode)
}

// string sIP = 2;
inline void ServerRegisterRet::clear_sip() {
  sip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerRegisterRet::sip() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegisterRet.sIP)
  return sip_.GetNoArena();
}
inline void ServerRegisterRet::set_sip(const ::std::string& value) {
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.ServerRegisterRet.sIP)
}
#if LANG_CXX11
inline void ServerRegisterRet::set_sip(::std::string&& value) {
  
  sip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.ServerRegisterRet.sIP)
}
#endif
inline void ServerRegisterRet::set_sip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.ServerRegisterRet.sIP)
}
inline void ServerRegisterRet::set_sip(const char* value, size_t size) {
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.ServerRegisterRet.sIP)
}
inline ::std::string* ServerRegisterRet::mutable_sip() {
  
  // @@protoc_insertion_point(field_mutable:svrData.ServerRegisterRet.sIP)
  return sip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerRegisterRet::release_sip() {
  // @@protoc_insertion_point(field_release:svrData.ServerRegisterRet.sIP)
  
  return sip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerRegisterRet::set_allocated_sip(::std::string* sip) {
  if (sip != NULL) {
    
  } else {
    
  }
  sip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sip);
  // @@protoc_insertion_point(field_set_allocated:svrData.ServerRegisterRet.sIP)
}

// int32 nPort = 3;
inline void ServerRegisterRet::clear_nport() {
  nport_ = 0;
}
inline ::google::protobuf::int32 ServerRegisterRet::nport() const {
  // @@protoc_insertion_point(field_get:svrData.ServerRegisterRet.nPort)
  return nport_;
}
inline void ServerRegisterRet::set_nport(::google::protobuf::int32 value) {
  
  nport_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerRegisterRet.nPort)
}

// -------------------------------------------------------------------

// ServerLoadInfo

// int32 nMaxClient = 1;
inline void ServerLoadInfo::clear_nmaxclient() {
  nmaxclient_ = 0;
}
inline ::google::protobuf::int32 ServerLoadInfo::nmaxclient() const {
  // @@protoc_insertion_point(field_get:svrData.ServerLoadInfo.nMaxClient)
  return nmaxclient_;
}
inline void ServerLoadInfo::set_nmaxclient(::google::protobuf::int32 value) {
  
  nmaxclient_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerLoadInfo.nMaxClient)
}

// int32 nNowClient = 2;
inline void ServerLoadInfo::clear_nnowclient() {
  nnowclient_ = 0;
}
inline ::google::protobuf::int32 ServerLoadInfo::nnowclient() const {
  // @@protoc_insertion_point(field_get:svrData.ServerLoadInfo.nNowClient)
  return nnowclient_;
}
inline void ServerLoadInfo::set_nnowclient(::google::protobuf::int32 value) {
  
  nnowclient_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerLoadInfo.nNowClient)
}

// int32 nPort = 3;
inline void ServerLoadInfo::clear_nport() {
  nport_ = 0;
}
inline ::google::protobuf::int32 ServerLoadInfo::nport() const {
  // @@protoc_insertion_point(field_get:svrData.ServerLoadInfo.nPort)
  return nport_;
}
inline void ServerLoadInfo::set_nport(::google::protobuf::int32 value) {
  
  nport_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerLoadInfo.nPort)
}

// string sIP = 4;
inline void ServerLoadInfo::clear_sip() {
  sip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ServerLoadInfo::sip() const {
  // @@protoc_insertion_point(field_get:svrData.ServerLoadInfo.sIP)
  return sip_.GetNoArena();
}
inline void ServerLoadInfo::set_sip(const ::std::string& value) {
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.ServerLoadInfo.sIP)
}
#if LANG_CXX11
inline void ServerLoadInfo::set_sip(::std::string&& value) {
  
  sip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.ServerLoadInfo.sIP)
}
#endif
inline void ServerLoadInfo::set_sip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.ServerLoadInfo.sIP)
}
inline void ServerLoadInfo::set_sip(const char* value, size_t size) {
  
  sip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.ServerLoadInfo.sIP)
}
inline ::std::string* ServerLoadInfo::mutable_sip() {
  
  // @@protoc_insertion_point(field_mutable:svrData.ServerLoadInfo.sIP)
  return sip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ServerLoadInfo::release_sip() {
  // @@protoc_insertion_point(field_release:svrData.ServerLoadInfo.sIP)
  
  return sip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ServerLoadInfo::set_allocated_sip(::std::string* sip) {
  if (sip != NULL) {
    
  } else {
    
  }
  sip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sip);
  // @@protoc_insertion_point(field_set_allocated:svrData.ServerLoadInfo.sIP)
}

// int32 nSubServerID = 5;
inline void ServerLoadInfo::clear_nsubserverid() {
  nsubserverid_ = 0;
}
inline ::google::protobuf::int32 ServerLoadInfo::nsubserverid() const {
  // @@protoc_insertion_point(field_get:svrData.ServerLoadInfo.nSubServerID)
  return nsubserverid_;
}
inline void ServerLoadInfo::set_nsubserverid(::google::protobuf::int32 value) {
  
  nsubserverid_ = value;
  // @@protoc_insertion_point(field_set:svrData.ServerLoadInfo.nSubServerID)
}

// -------------------------------------------------------------------

// UpdateServerLoad

// int32 nClientCountNow = 1;
inline void UpdateServerLoad::clear_nclientcountnow() {
  nclientcountnow_ = 0;
}
inline ::google::protobuf::int32 UpdateServerLoad::nclientcountnow() const {
  // @@protoc_insertion_point(field_get:svrData.UpdateServerLoad.nClientCountNow)
  return nclientcountnow_;
}
inline void UpdateServerLoad::set_nclientcountnow(::google::protobuf::int32 value) {
  
  nclientcountnow_ = value;
  // @@protoc_insertion_point(field_set:svrData.UpdateServerLoad.nClientCountNow)
}

// int32 nClientCountMax = 2;
inline void UpdateServerLoad::clear_nclientcountmax() {
  nclientcountmax_ = 0;
}
inline ::google::protobuf::int32 UpdateServerLoad::nclientcountmax() const {
  // @@protoc_insertion_point(field_get:svrData.UpdateServerLoad.nClientCountMax)
  return nclientcountmax_;
}
inline void UpdateServerLoad::set_nclientcountmax(::google::protobuf::int32 value) {
  
  nclientcountmax_ = value;
  // @@protoc_insertion_point(field_set:svrData.UpdateServerLoad.nClientCountMax)
}

// -------------------------------------------------------------------

// AddNewClient

// -------------------------------------------------------------------

// DelClient

// int32 nClientID = 1;
inline void DelClient::clear_nclientid() {
  nclientid_ = 0;
}
inline ::google::protobuf::int32 DelClient::nclientid() const {
  // @@protoc_insertion_point(field_get:svrData.DelClient.nClientID)
  return nclientid_;
}
inline void DelClient::set_nclientid(::google::protobuf::int32 value) {
  
  nclientid_ = value;
  // @@protoc_insertion_point(field_set:svrData.DelClient.nClientID)
}

// -------------------------------------------------------------------

// ClientToken

// string sEtoken = 1;
inline void ClientToken::clear_setoken() {
  setoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ClientToken::setoken() const {
  // @@protoc_insertion_point(field_get:svrData.ClientToken.sEtoken)
  return setoken_.GetNoArena();
}
inline void ClientToken::set_setoken(const ::std::string& value) {
  
  setoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.ClientToken.sEtoken)
}
#if LANG_CXX11
inline void ClientToken::set_setoken(::std::string&& value) {
  
  setoken_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.ClientToken.sEtoken)
}
#endif
inline void ClientToken::set_setoken(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  setoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.ClientToken.sEtoken)
}
inline void ClientToken::set_setoken(const char* value, size_t size) {
  
  setoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.ClientToken.sEtoken)
}
inline ::std::string* ClientToken::mutable_setoken() {
  
  // @@protoc_insertion_point(field_mutable:svrData.ClientToken.sEtoken)
  return setoken_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ClientToken::release_setoken() {
  // @@protoc_insertion_point(field_release:svrData.ClientToken.sEtoken)
  
  return setoken_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientToken::set_allocated_setoken(::std::string* setoken) {
  if (setoken != NULL) {
    
  } else {
    
  }
  setoken_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), setoken);
  // @@protoc_insertion_point(field_set_allocated:svrData.ClientToken.sEtoken)
}

// bytes sSecret = 2;
inline void ClientToken::clear_ssecret() {
  ssecret_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ClientToken::ssecret() const {
  // @@protoc_insertion_point(field_get:svrData.ClientToken.sSecret)
  return ssecret_.GetNoArena();
}
inline void ClientToken::set_ssecret(const ::std::string& value) {
  
  ssecret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.ClientToken.sSecret)
}
#if LANG_CXX11
inline void ClientToken::set_ssecret(::std::string&& value) {
  
  ssecret_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.ClientToken.sSecret)
}
#endif
inline void ClientToken::set_ssecret(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ssecret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.ClientToken.sSecret)
}
inline void ClientToken::set_ssecret(const void* value, size_t size) {
  
  ssecret_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.ClientToken.sSecret)
}
inline ::std::string* ClientToken::mutable_ssecret() {
  
  // @@protoc_insertion_point(field_mutable:svrData.ClientToken.sSecret)
  return ssecret_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ClientToken::release_ssecret() {
  // @@protoc_insertion_point(field_release:svrData.ClientToken.sSecret)
  
  return ssecret_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ClientToken::set_allocated_ssecret(::std::string* ssecret) {
  if (ssecret != NULL) {
    
  } else {
    
  }
  ssecret_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ssecret);
  // @@protoc_insertion_point(field_set_allocated:svrData.ClientToken.sSecret)
}

// -------------------------------------------------------------------

// LoadPlayerData

// int64 clientid = 1;
inline void LoadPlayerData::clear_clientid() {
  clientid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LoadPlayerData::clientid() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.clientid)
  return clientid_;
}
inline void LoadPlayerData::set_clientid(::google::protobuf::int64 value) {
  
  clientid_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.clientid)
}

// string account = 2;
inline void LoadPlayerData::clear_account() {
  account_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoadPlayerData::account() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.account)
  return account_.GetNoArena();
}
inline void LoadPlayerData::set_account(const ::std::string& value) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.account)
}
#if LANG_CXX11
inline void LoadPlayerData::set_account(::std::string&& value) {
  
  account_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.LoadPlayerData.account)
}
#endif
inline void LoadPlayerData::set_account(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.LoadPlayerData.account)
}
inline void LoadPlayerData::set_account(const char* value, size_t size) {
  
  account_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.LoadPlayerData.account)
}
inline ::std::string* LoadPlayerData::mutable_account() {
  
  // @@protoc_insertion_point(field_mutable:svrData.LoadPlayerData.account)
  return account_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoadPlayerData::release_account() {
  // @@protoc_insertion_point(field_release:svrData.LoadPlayerData.account)
  
  return account_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoadPlayerData::set_allocated_account(::std::string* account) {
  if (account != NULL) {
    
  } else {
    
  }
  account_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), account);
  // @@protoc_insertion_point(field_set_allocated:svrData.LoadPlayerData.account)
}

// string name = 3;
inline void LoadPlayerData::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoadPlayerData::name() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.name)
  return name_.GetNoArena();
}
inline void LoadPlayerData::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.name)
}
#if LANG_CXX11
inline void LoadPlayerData::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.LoadPlayerData.name)
}
#endif
inline void LoadPlayerData::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.LoadPlayerData.name)
}
inline void LoadPlayerData::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.LoadPlayerData.name)
}
inline ::std::string* LoadPlayerData::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:svrData.LoadPlayerData.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoadPlayerData::release_name() {
  // @@protoc_insertion_point(field_release:svrData.LoadPlayerData.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoadPlayerData::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:svrData.LoadPlayerData.name)
}

// int64 guid = 4;
inline void LoadPlayerData::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LoadPlayerData::guid() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.guid)
  return guid_;
}
inline void LoadPlayerData::set_guid(::google::protobuf::int64 value) {
  
  guid_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.guid)
}

// int32 sex = 5;
inline void LoadPlayerData::clear_sex() {
  sex_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::sex() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.sex)
  return sex_;
}
inline void LoadPlayerData::set_sex(::google::protobuf::int32 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.sex)
}

// int32 job = 6;
inline void LoadPlayerData::clear_job() {
  job_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::job() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.job)
  return job_;
}
inline void LoadPlayerData::set_job(::google::protobuf::int32 value) {
  
  job_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.job)
}

// int32 level = 7;
inline void LoadPlayerData::clear_level() {
  level_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::level() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.level)
  return level_;
}
inline void LoadPlayerData::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.level)
}

// int32 createtime = 8;
inline void LoadPlayerData::clear_createtime() {
  createtime_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::createtime() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.createtime)
  return createtime_;
}
inline void LoadPlayerData::set_createtime(::google::protobuf::int32 value) {
  
  createtime_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.createtime)
}

// int32 logintime = 9;
inline void LoadPlayerData::clear_logintime() {
  logintime_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::logintime() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.logintime)
  return logintime_;
}
inline void LoadPlayerData::set_logintime(::google::protobuf::int32 value) {
  
  logintime_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.logintime)
}

// int32 mapid = 10;
inline void LoadPlayerData::clear_mapid() {
  mapid_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerData::mapid() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.mapid)
  return mapid_;
}
inline void LoadPlayerData::set_mapid(::google::protobuf::int32 value) {
  
  mapid_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.mapid)
}

// float x = 11;
inline void LoadPlayerData::clear_x() {
  x_ = 0;
}
inline float LoadPlayerData::x() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.x)
  return x_;
}
inline void LoadPlayerData::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.x)
}

// float y = 12;
inline void LoadPlayerData::clear_y() {
  y_ = 0;
}
inline float LoadPlayerData::y() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.y)
  return y_;
}
inline void LoadPlayerData::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.y)
}

// float z = 13;
inline void LoadPlayerData::clear_z() {
  z_ = 0;
}
inline float LoadPlayerData::z() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.z)
  return z_;
}
inline void LoadPlayerData::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.z)
}

// bytes data = 14;
inline void LoadPlayerData::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LoadPlayerData::data() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerData.data)
  return data_.GetNoArena();
}
inline void LoadPlayerData::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerData.data)
}
#if LANG_CXX11
inline void LoadPlayerData::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:svrData.LoadPlayerData.data)
}
#endif
inline void LoadPlayerData::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:svrData.LoadPlayerData.data)
}
inline void LoadPlayerData::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:svrData.LoadPlayerData.data)
}
inline ::std::string* LoadPlayerData::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:svrData.LoadPlayerData.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LoadPlayerData::release_data() {
  // @@protoc_insertion_point(field_release:svrData.LoadPlayerData.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LoadPlayerData::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:svrData.LoadPlayerData.data)
}

// -------------------------------------------------------------------

// LoadPlayerDataRet

// int32 nRetCode = 1;
inline void LoadPlayerDataRet::clear_nretcode() {
  nretcode_ = 0;
}
inline ::google::protobuf::int32 LoadPlayerDataRet::nretcode() const {
  // @@protoc_insertion_point(field_get:svrData.LoadPlayerDataRet.nRetCode)
  return nretcode_;
}
inline void LoadPlayerDataRet::set_nretcode(::google::protobuf::int32 value) {
  
  nretcode_ = value;
  // @@protoc_insertion_point(field_set:svrData.LoadPlayerDataRet.nRetCode)
}

// -------------------------------------------------------------------

// ServerLog

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace svrData

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::svrData::ServerRegisterRet_EC> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::svrData::ServerRegisterRet_EC>() {
  return ::svrData::ServerRegisterRet_EC_descriptor();
}
template <> struct is_proto_enum< ::svrData::LoadPlayerDataRet_EC> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::svrData::LoadPlayerDataRet_EC>() {
  return ::svrData::LoadPlayerDataRet_EC_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerMsg_2eproto_INCLUDED
